package me.bramar.extracommands.customenchants;

public enum EventType {
	TICK, DAMAGED, DAMAGE_BY_ENTITY, DAMAGE_BY_BLOCK, BLOCK_BREAK, BLOCK_PLACE, CONSUME_ITEM,
	LAND, BREAK_ITEM, INTERACT_ENTITY, INTERACT_AT_ENTITY, INTERACT, XP_CHANGE, DAMAGED_BY_PROJECTILE,
	PLAYER_DAMAGE_ENTITY, BLOCK_DROP_ITEM, BLOCK_DROP_EXP /* Checks */
	// Entities
	, ENTITY_DAMAGED_BY_ENTITY, ENTITY_EXPLODE, POTION_SPLASH, SHOOT_BOW, PROJECTILE_HIT, PROJECTILE_LAUNCH,
	ENTITY_DAMAGED_BY_ARROW/* Checks if its enchanted (arrow) */, ENTITY_DEATH_EVENT, ENTITY_DAMAGE_EVENT
}
